services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434/api/tags || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  ollama-init:
    image: ollama/ollama
    depends_on:
      - ollama
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=${OLLAMA_URL}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME}
    entrypoint: []
    env_file:
      - .env.dev
    command: >
      sh -c "
        echo 'Waiting for Ollama to be ready...' &&
        sleep 3 &&
        echo 'Checking if model ${LLM_MODEL_NAME} exists...' &&
        if ! OLLAMA_HOST=${OLLAMA_URL} ollama list | grep -q '${LLM_MODEL_NAME}'; then
          echo 'Model ${LLM_MODEL_NAME} not found, pulling...' &&
          OLLAMA_HOST=${OLLAMA_URL} ollama pull ${LLM_MODEL_NAME}
        else
          echo 'Model ${LLM_MODEL_NAME} already exists, skipping pull.'
        fi &&
        echo 'Model setup complete!'
      "
    restart: "no"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped


  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  db_init:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile.db_init
    depends_on:
      - postgres
    env_file:
      - .env.dev
    volumes:
      - ./backend/db_init:/app/db_init
    command: >
      sh -c "
        until pg_isready -h $POSTGRES_HOST -p 5432; do
          echo 'Waiting for Postgres...'
          sleep 1
        done
        python /app/db_init/db_init.py
      "
    restart: "no"

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - .env.dev
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend:/app/backend
      - ./uploads:/app/uploads
    depends_on:
      ollama-init:
        condition: service_completed_successfully
      # qdrant:
      #   condition: service_healthy
      # postgres:
      #   condition: service_healthy
      db_init:
        condition: service_completed_successfully


  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  ollama_data:
  qdrant_data:
  postgres_data: